[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "packaging",

    "numpy",
    "torch-mlir>=20220428.420",
    "iree-compiler>=20220427.13",
    "iree-runtime>=20220427.13",
]
build-backend = "setuptools.build_meta"
